menu:
  Home: /
  Archives: /archives

widgets: 
#- search
- category
- tagcloud

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics: true
rss: /atom.xml
